# ===== Ambiente LOCAL (docker-compose: mysql:8 root/root) =====
spring.datasource.url=jdbc:mysql://localhost:3306/comanda_digital?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true

# Secret de desenvolvimento (fixo - so para LOCAL). Minimo 64 chars para HS256.
app.jwt.secret=local-dev-secret-comanda-digital-unasp-sp-2026-troque-em-producao-ok
app.jwt.expiration-ms=28800000

# CORS - Angular em dev
app.cors.allowed-origins=http://localhost:4200
